name = "FLagHada"
uuid = "5b931c05-3fa0-4811-a758-60deaf45e684"
authors = ["Averil Aussedat <averil.aussedat@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
